### ISSUE TITLE
Exception in Texture.h when trying to import a texture

### ISSUE THREAD

**Issue by softdrawss** [CITM-UPC/LilacEngine#5]
@pepcots I'm facing some issues relating to the importation of Textures when the constructor is called. All the data relating to the mesh and the texture seems to work fine, but whenever it tries to generate the MipMap an exception is produced.

Here is the code from the constructor:
<img width="434" alt="Captura de pantalla 2023-11-01 193930" src="https://github.com/CITM-UPC/LilacEngine/assets/99959289/b08a6ca3-0981-41a9-943b-0862df0c0b80">

And the exception:
<img width="206" alt="Captura de pantalla 2023-11-01 194410" src="https://github.com/CITM-UPC/LilacEngine/assets/99959289/a4d6b15a-2157-4e9a-a9ce-e4be745619de">

I am not sure whether if it is relating to the variable _id when loading the texture in VRAM, as in the original code that should be equal to 1 and in my project it is equal to 2.

**Comment by pepcots** [comment]
Hi Julia!Make sure to call glewInit() just after the gl context is created. Best place to do that is in the GameEngine constructor (but be sure the constructor is called after the glwindow and glcontext is created in the editor!generatemipmaçs is an opengl extension and needs to be initialized (this is what glewInit does, initialize all gl extensions)Let me knowif it works for you!

**Comment by pepcots** [comment]
Btw, if it works for you, please, share it with the rest of the class!

**Comment by pepcots** [comment]
I think, some of your class mates are facing same issue: https://github.com/CITM-UPC/VertX-Game-Engine/issues/1

**Comment by softdrawss** [comment]
Thank you! That was it.
